site_name: Stuart Christhilf

theme:
    name: simple-blog

nav:
  - Home: 'index.md'
  - About: 'about.md'
  - Engineering Projects: 'Engineering.md'
  - Coding Projects: 'coding.md'

markdown_extensions:
  - attr_list